# Funding for ITM Trading Enterprise System
# Support the development of this enterprise mineral trading platform

github: mrye12
# patreon: your_patreon_username
# ko_fi: your_ko_fi_username

custom:
  - "https://github.com/mrye12/nextjs-boilerplate"
  - "mailto:support@itmtrading.com"
